# Arucode Ids
BOT_ID = 69
POST_ID  = 92

#  colors
BLUE = (255, 0, 0)
GREEN = (0, 255, 0)
RED = (0, 0, 255)
YELLOW = (0, 165, 255)

MOVEMENT_SPEED = 10
ROTATION_SPEED = 4

# Sample ms to set calibration        [start, stop, step]
BOT_CALIBRATION_MOVEMENT_MS_SAMPLES = [50, 1400, 50]
BOT_CALIBRATION_ROTATION_MS_SAMPLES = [20, 360, 10]

# Sleep constants
SLEEP_BEFORE_GOAL = 0.5
SLEEP_AFTER_GOAL = 0.5
SLEEP_AFTER_MOVEMENT = 0.5
SLEEP_BALL_NOT_FOUND = 1 # sleep when bot center or ball not found
SLEEP_AFTER_EACH_LOOP=0.3
SLEEP_FOR_KEY_PRESS = 500 # in ms
SLEEP_AFTER_CALIBRATION_MOVEMENT = 1
SLEEP_CORNER_SELECTION_LOOP = 0.5
SLEEP_ARUCO_NOT_FOUND_RECALCULATE = 0.2
MOVEMENT_CORRECTION_SLEEP = 0.3
SLEEP_BEFORE_TAKING_FRAME = 0
# cv2.waitKey wait
SLEEP_AFTER_DISPLAYING = 1 # in ms


# measurement constants
FIELD_LENGTH = 239
FIELD_WIDTH = 182
CORNER_TO_POST_LENGTH = 68
POST_LENGTH = 45
DEFAULT_POSITION_TO_POST_LENGTH = 23
TRIM_LENGTH = 15
BOT_MOVEMENT_TRIM_LENGTH = 8
EXTENDED_POINT_OFFSET = 20
EDGE_BALL_ROTATION_DISTANCE = 12
EDGE_BALL_MOVEMENT_DISTANCE = 15

MOVEMENT_REVERSE_DICT = {
    'left': 'right', 'right': 'left', 'forward': 'backward',
    'backward': 'forward','stop':'stop'}

# flags
MOVEMENT_CORRECTION_PERCENTAGES = [0.8,0.5,1] # each value percentageis a percentage