# Arucode Ids
BOT_ID = 69
POST_ID  = 92

#  colors
BLUE = (255, 0, 0)
GREEN = (0, 255, 0)
RED = (0, 0, 255)
YELLOW = (0, 165, 255)
GREY = (128, 128, 128)

MOVEMENT_SPEED = 8
ROTATION_SPEED = 4

# Sample ms to set calibration        [start, stop, step]
BOT_CALIBRATION_MOVEMENT_MS_SAMPLES = [50, 1400, 50]
BOT_CALIBRATION_ROTATION_MS_SAMPLES = [20, 360, 10]

# Sleep constants
SLEEP_BEFORE_GOAL = 0.1
SLEEP_AFTER_GOAL = 0.2
SLEEP_AFTER_MOVEMENT = 0.01
SLEEP_BALL_NOT_FOUND = 1 # sleep when bot center or ball not found
SLEEP_AFTER_EACH_LOOP = 0.1
SLEEP_FOR_KEY_PRESS = 1 # in ms
SLEEP_AFTER_CALIBRATION_MOVEMENT = 1
SLEEP_CORNER_SELECTION_LOOP = 0.5
SLEEP_ARUCO_NOT_FOUND_RECALCULATE = 0.2
MOVEMENT_CORRECTION_SLEEP = 0.1
SLEEP_AFTER_DEFENSE = 0.3
# cv2.waitKey wait
SLEEP_AFTER_DISPLAYING = 1 # in ms
SLEEP_BEFORE_TAKING_FRAME = 0


# measurement constants
FIELD_LENGTH = 239
FIELD_WIDTH = 182
CORNER_TO_POST_LENGTH = 68
POST_LENGTH = 45
DEFAULT_POSITION_TO_POST_LENGTH = 23
TRIM_LENGTH = 10
BOT_MOVEMENT_TRIM_LENGTH = 8
EXTENDED_POINT_OFFSET = 20
EDGE_BALL_ROTATION_DISTANCE = 8
EDGE_BALL_MOVEMENT_DISTANCE = 15


FORWARD_OFFENCE_POINT_DISTANCE_AFTER_CENTER = 20
DEFENSE_POINT_DISTANCE_FROM_DEFAULT_POINT = 25

AVOIDANCE_DISTANCE = 15
PIT_STOP_DISTANCE = 30

MOVEMENT_REVERSE_DICT = {
    'left': 'right', 'right': 'left', 'forward': 'backward',
    'backward': 'forward','stop':'stop'}

# flags
RANDOM_MOVEMENT_SPEED = 3
RANDOM_MOVEMENT_DELAY_RANGE = [100, 800]
RANDOM_MOVEMENT_DIRECTIONS = ['forward', 'backward', 'left', 'right']
FORWARD_MOVEMENT_DELAY = 1000

# each value percentageis a percentage
MOVEMENT_CORRECTION_PERCENTAGES = [0.6, 0.5, 0.5, 1]
MOVEMENT_ERROR_ALLOWED = 15
ORIENT_ROTATION_ERROR_ALOWED = 1

IS_ARUCO_WORKING = True

DEFENCE_INITIAL_MOVEMENTS = [['right',278],['backward',270]]
DEFENCE_LOOP_MOVEMENTS = [['forward',442],['backward',442]]